version: '3.8'
services:
  jenkins-master:
    build: ./jenkins
    container_name: jenkins-master
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/var/jenkins_home/jenkins.yaml
      - ./jobs.groovy:/var/jenkins_home/jobs.groovy
      - ./kubeconfig:/var/jenkins_home/kubeconfig
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network
    restart: unless-stopped
    
  # jenkins-agent:
  #   image: jenkins/inbound-agent:latest
  #   container_name: jenkins-agent
  #   privileged: true
  #   user: root
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - agent_workspace:/home/jenkins/agent
  #   environment:
  #     - JENKINS_URL=http://jenkins-master:8080
  #     - JENKINS_AGENT_NAME=docker-agent
  #     - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
  #     - JENKINS_SECRET=${JENKINS_AGENT_SECRET}
  #     - JENKINS_WEB_SOCKET=true
  #   depends_on:
  #     - jenkins-master
  #   networks:
  #     - jenkins-network
  #   restart: unless-stopped

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
  # agent_workspace: