version: '3.8'
services:
  jenkins-master:
    build: ./jenkins
    container_name: jenkins-master
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/var/jenkins_home/jenkins.yaml
      - ./jobs.groovy:/var/jenkins_home/jobs.groovy
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.example
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network
    restart: unless-stopped

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
  # agent_workspace: